    *____________________________________________________________________________________________________________________________________*

															*DESCRIPTIVE STATISTICS*
														
														*Financial Literacy Pilot in Brazil*
    *____________________________________________________________________________________________________________________________________*

	*----------------------------------------------------------------------------------------------------------------------*
	*TABLES FOR THE PAPER, in the order they appear in it. Each block loads its own data and writes
	*a LaTeX fragment to $textables, which the paper inputs. Anything not used by the paper sits at
	*the end of this file, commented out.
	*----------------------------------------------------------------------------------------------------------------------*

	**
	*Table A1 -- Sample selected for the pilot study
	*---------------------------------------------------------------------------------------------------------------------*
	{	//The Figure below is copied from Table 1 ("Amostra selecionada para o piloto") of the pilot's
		//implementation report (World Bank, August 2016). Report layout, by school type:
		//
		//                              Joinville                   Manaus                        Total
		//                          frame    T    C          frame  drawn    T    C           T     C    all
		//     Only grades 1-5         20   10   10            202     36   18   18          28    28     56
		//     Only grades 6-9          2    1    1             35     28   14   14          15    15     30
		//     Grades 1-9              50   25   25             65     65   33   32          58    57    115
		//     Total                   72   36   36            302    129   65   64         101   100    201
		//
		//Row (2) splits the 36 and 28 schools drawn in Manaus over the four quartiles of the 2013 IDEB
		//(36/4 = 9 and 28/4 = 7). Columns follow the paper's stratum labels: A.1-A.3 are Joinville and
		//B.1-B.3 are Manaus, each in the order grades 1-5, grades 6-9, grades 1-9.
		clear
		input 	str93 row  str12 a1  str11 a2  str11 a3  str12 b1  str11 b2  str11 b3  str30 total
			"% Generated by Do files/2_Descriptives.do (Table A1 block) -- do not edit by hand."	""	""	""	""	""	""	""
			"% Figures from Table 1 of the pilot's implementation report (World Bank, August 2016)."	""	""	""	""	""	""	""
			"(1) \textbf{Sampling frame}"				"\textbf{20}"	"\textbf{2}"	"\textbf{50}"	"\textbf{202}"	"\textbf{35}"	"\textbf{65}"	"\textbf{374} \\"
			"(2) Schools drawn from each IDEB quartile"	"---"			"---"			"---"			"9"				"7"				"---"			"\\"
			"(3) \textbf{= Schools in the study}"		"\textbf{20}"	"\textbf{2}"	"\textbf{50}"	"\textbf{36}"	"\textbf{28}"	"\textbf{65}"	"\textbf{201} \\ \addlinespace"
			"(4) Assigned to treatment"					"10"			"1"				"25"			"18"			"14"			"33"			"101 \\"
			"(5) Assigned to control"					"10"			"1"				"25"			"18"			"14"			"32"			"100 \\"
		end
		list, clean noobs																	//check the numbers in the log
		export 	delimited using "$textables/TableA1.tex", delimiter("&") novarnames replace
	}

	**
	*Table A2 -- Program implementation according to students and teachers
	*---------------------------------------------------------------------------------------------------------------------*
	* Panel A: student questionnaire (SE60 fin-lit classes, Yes=2; SE61 when received the book;
	*          SE62 teacher used the book). Students in grades 5/7/9 only (no socio questionnaire
	*          in grade 3): Pooled = 5/7/9, Elementary = 5, Middle = 7/9.
	* Panel B: teacher questionnaire, stacked base, one row per teacher (Yes=1 in every item):
	*          T20 training, T17 teacher book, T18 books distributed, T38 taught >=1 class,
	*          T19 used the student book. Pooled = all, Elementary = grades 3/5, Middle = 7/9.
	* Shares are UNCONDITIONAL (missing kept in the denominator; "Did not answer" rows shown).
	* Diff = control - treatment, the raw gap between the two group means, with stars from a
	* regression on treatment and the strata dummies clustered at the school level.
	* Every cell is computed directly -- group means with summarize, and the difference with the
	* regression above -- replicating what iebaltab produced here before, cell by cell. The
	* three samples of the column groups sit in $pooled, $elementary and $middle, set at the top
	* of each panel. All the LaTeX markup lives inside three small helpers: prow and qrow write
	* the panel and question headers, trow computes and writes one data row (C, T and Diff for
	* the three samples), and orow writes the Observations row of a panel.
	*==========================================================================================*
	{
		*---------- helpers ----------
		cap program drop prow									//panel header, in bold italics
		program define prow
			args title
			local title : subinstr local title "%" "\%", all
			file write tex `"\multicolumn{10}{l}{\textit{\textbf{`title'}}} \\"' _n
		end

		cap program drop qrow									//question header, in italics
		program define qrow
			args title
			local title : subinstr local title "%" "\%", all
			file write tex `"\multicolumn{10}{l}{\textit{`title'}} \\"' _n
		end

		cap program drop trow									//one data row: C, T and Diff per sample
		program define trow
			args var lab
			local lab : subinstr local lab "%" "\%", all
			file write tex `"\quad `lab'"'
			foreach cond in "$pooled" "$elementary" "$middle" {
				qui summ `var' if `cond' & d == 0
				local mc = r(mean)
				qui summ `var' if `cond' & d == 1
				local mt = r(mean)
				qui reg `var' d $estrato if `cond', vce(cluster cd_escola)
				local p  = 2*ttail(e(df_r), abs(_b[d]/_se[d]))
				local st = cond(`p' < .01, "***", cond(`p' < .05, "**", cond(`p' < .1, "*", "")))
				file write tex " & " (strtrim(string(`mc',"%12.1f"))) " & " (strtrim(string(`mt',"%12.1f"))) ///
					" & " (strtrim(string(`mc' - `mt',"%12.1f"))) "`st'"
			}
			file write tex " \\" _n
		end

		cap program drop orow									//Observations row of a panel
		program define orow
			file write tex "\quad Observations"
			foreach cond in "$pooled" "$elementary" "$middle" {
				qui count if `cond' & d == 0
				local nc = r(N)
				qui count if `cond' & d == 1
				file write tex " & " (strtrim(string(`nc',"%9.0fc"))) " & " (strtrim(string(r(N),"%9.0fc"))) " & "
			}
			file write tex " \\" _n
		end

		file open  tex using "$textables/TableA2.tex", write replace
		file write tex "% Generated by Do files/2_Descriptives.do -- data rows only, do not edit by hand." _n
		file write tex "% The shell (caption, headers, notes, source) lives in Paper/Fin_Lit_Paper.tex." _n

		*---------- Panel A: students ----------
		use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
		keep if serie > 3
		global pooled		"serie >  3"
		global elementary	"serie == 5"
		global middle		"serie >  5"

		gen a1  = 100*(socio_rp_60 == 2)                       //had fin-lit classes: Yes (label "no": No=1, Yes=2)
		gen a2  = 100*(socio_rp_60 == 1)                       //                     No
		gen a3  = 100*missing(socio_rp_60)
		gen a4  = 100*(socio_rp_61 == 1)                       //received: beginning of the year
		gen a5  = 100*(socio_rp_61 == 2)                       //          middle of the year
		gen a6  = 100*(socio_rp_61 == 3)                       //          end of the year
		gen a7  = 100*(socio_rp_61 == 4)                       //          haven't received
		gen a8  = 100*missing(socio_rp_61)
		gen a9  = 100*(socio_rp_62 == 3)                       //teacher used the book: received and used
		gen a10 = 100*(socio_rp_62 == 2)                       //                       received but haven't used
		gen a11 = 100*(socio_rp_62 == 1)                       //                       haven't received
		gen a12 = 100*missing(socio_rp_62)

		prow "Panel A. Implementation according to students (% of students)"
		qrow "Did you have financial education classes?"
		trow a1  "Yes"
		trow a2  "No"
		trow a3  "Did not answer"
		qrow "When did you receive the financial education textbook?"
		trow a4  "Beginning of the year"
		trow a5  "By the middle of the year"
		trow a6  "In the end of the year"
		trow a7  "Haven't received"
		trow a8  "Did not answer"
		qrow "Has your teacher used the financial education textbook?"
		trow a9  "Received and used"
		trow a10 "Received but haven't used"
		trow a11 "Haven't received"
		trow a12 "Did not answer"
		orow

		file write tex "\addlinespace" _n

		*---------- Panel B: teachers (one row per teacher) ----------
		use "$dtinter/Teacher's data_long.dta", clear
		merge m:1 cd_escola using "$dtinter/Treatment and Control Groups.dta", keep(match master) nogen
		gen d = resultado
		global pooled		"inlist(cd_etapa_aplicacao_turma, 3, 5, 7, 9)"	//all four pilot grades = every teacher in
		global elementary	"cd_etapa_aplicacao_turma < 7"					//the file (683 rows, all matched in the
		global middle		"cd_etapa_aplicacao_turma > 5"					//merge above, d never missing -- checked)

		gen b1  = 100*(prof_rp_20_ == 1)                       //received training: Yes
		gen b2  = 100*(prof_rp_20_ == 2)                       //                   No
		gen b3  = 100*missing(prof_rp_20_)
		gen b4  = 100*(prof_rp_17_ == 1)                       //received the teacher book
		gen b5  = 100*(prof_rp_17_ == 2)
		gen b6  = 100*missing(prof_rp_17_)
		gen b7  = 100*(prof_rp_18_ == 1)                       //student books distributed
		gen b8  = 100*(prof_rp_18_ == 2)
		gen b9  = 100*missing(prof_rp_18_)
		gen b10 = 100*(prof_rp_19_ == 1)                       //used the student book
		gen b11 = 100*(prof_rp_19_ == 2)
		gen b12 = 100*missing(prof_rp_19_)
		forvalues k = 1/8 {                                    //number of fin-lit classes taught (T38: 8 = top category)
			gen b`=12+`k'' = 100*(prof_rp_38_ == `k')
		}
		gen b21 = 100*missing(prof_rp_38_)
		forvalues k = 1/4 {                                    //share of the textbook covered (T40: <40, 40-60, 60-80, >80)
			gen b`=21+`k'' = 100*(prof_rp_40_ == `k')
		}
		gen b26 = 100*missing(prof_rp_40_)
		gen b27 = 100*inlist(prof_rp_39_, 1, 2, 3)             //when taught (T39): codes 1-3 = beginning of the year
		gen b28 = 100*inlist(prof_rp_39_, 4, 5, 6)             //                   codes 4-6 = end of the year
		gen b29 = 100*(prof_rp_39_ == 7)                       //                   code  7   = all year
		gen b30 = 100*missing(prof_rp_39_)

		prow "Panel B. Implementation according to teachers (% of teachers)"
		qrow "Received training to use the textbook"
		trow b1  "Yes"
		trow b2  "No"
		trow b3  "Did not answer"
		qrow "Received the teacher book"
		trow b4  "Yes"
		trow b5  "No"
		trow b6  "Did not answer"
		qrow "Student books were distributed to the students"
		trow b7  "Yes"
		trow b8  "No"
		trow b9  "Did not answer"
		qrow "Used the student book"
		trow b10 "Yes"
		trow b11 "No"
		trow b12 "Did not answer"
		qrow "Number of financial education classes taught"
		forvalues k = 1/7 {
			trow b`=12+`k'' "`k'"
		}
		trow b20 "8 or more"
		trow b21 "Did not answer"
		qrow "When in the year was the subject taught?"
		trow b27 "First semester"
		trow b28 "Second semester"
		trow b29 "All year"
		trow b30 "Did not answer"
		qrow "Share of the textbook covered"
		trow b22 "Less than 40%"
		trow b23 "40%--60%"
		trow b24 "60%--80%"
		trow b25 "More than 80%"
		trow b26 "Did not answer"
		orow

		file close tex

		display "IMPLEMENTATION_TABLE_V2_DONE"
	}

	**
	*==========================================================================================*
	* Table A.4 -- Items used to construct the consumption and savings attitude indices
	* Reproduces the weights column from the same PCA that 1_Cleaning.do uses to build the two
	* indices: same items, same reversed coding, same sample, so the loadings are identical by
	* construction (we recompute rather than read 1_Cleaning's PCA.xlsx, which OneDrive can
	* drop silently). The statements and the answer-scale coding are fixed questionnaire text
	* and live here; the fragment carries the rows, the shell keeps the headers and notes.
	*==========================================================================================*
	{
		use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear

		**
		*The recoded items already live in the clean base (built by 1_Cleaning.do, positively
		*worded statements reversed there), so the same pca call reproduces the same loadings
		pca 	index_q42 index_q43 index_q44 index_q45 index_q46 index_q47 index_q48
		matrix 	L_c = e(L)

		pca 	index_q52 index_q53 index_q54 index_q55 index_q56 index_q57 index_q58 index_q59
		matrix 	L_s = e(L)

		**
		*One row per statement: text, the four scale codes as printed, and the first-component loading
		file open  tex using "$textables/TableA4.tex", write replace
		file write tex "% Generated by Do files/3_Descriptives.do -- data rows only, do not edit by hand." _n
		file write tex "% The shell (caption, headers, notes, source) lives in Paper/Fin_Lit_Paper.tex." _n

		file write tex "\textbf{Consumption questions} &       &       &       &       &  \\" _n
		local c_42 "I buy what I want, then I see how I can pay|1|2|3|4"
		local c_43 "I see no problem in owing money|1|2|3|4"
		local c_44 "If the brand is famous the product is of high quality|1|2|3|4"
		local c_45 "The best product is always the most expensive|1|2|3|4"
		local c_46 "I plan before spending my money|4|3|2|1"
		local c_47 "It is worthless to plan because the money comes from luck|1|2|3|4"
		local c_48 "Buy what I want is more important than planning|1|2|3|4"
		local r = 0
		foreach i in 42 43 44 45 46 47 48 {
			local ++r
			gettoken stmt rest : c_`i', parse("|")
			local rest = subinstr("`rest'", "|", " & ", .)
			local rest = substr("`rest'", 4, .)
			local w : display %4.2f L_c[`r', 1]
			file write tex "`stmt' & `rest' & `w' \\" _n
		}

		file write tex "      &       &       &       &       &  \\" _n
		file write tex "\textbf{Saving questions} &       &       &       &       &  \\" _n
		local s_52 "I think that saving money is important to avoid problems in the future|4|3|2|1"
		local s_53 "I feel safer when I can save some money|4|3|2|1"
		local s_54 "Saving some money is important to avoid debt|4|3|2|1"
		local s_55 "Buying everything I want is more important than putting the money together|1|2|3|4"
		local s_56 "Avoiding waste is also a way to save money|4|3|2|1"
		local s_57 "I try to use the products for longer|4|3|2|1"
		local s_58 "Whenever I can, I save money|4|3|2|1"
		local s_59 "I would rather spend the change on something I want than save the money for later|1|2|3|4"
		local r = 0
		foreach i in 52 53 54 55 56 57 58 59 {
			local ++r
			gettoken stmt rest : s_`i', parse("|")
			local rest = subinstr("`rest'", "|", " & ", .)
			local rest = substr("`rest'", 4, .)
			local w : display %4.2f L_s[`r', 1]
			file write tex "`stmt' & `rest' & `w' \\" _n
		}
		file close tex

		display "CSINDEX_TABLE_DONE"
	}

	**
	*==========================================================================================*
	* Tables A.5 and A.6 -- Balance tests for students and teachers
	* Same method as Table A.2, one vrow call per variable: C and T are the group means, with
	* their school-clustered SEs and Ns from a regression on a constant within each group, and
	* Diff is the raw gap C - T with stars from the p-value of a regression on treatment and
	* the strata dummies, clustered at the school level -- exactly what iebaltab reported here
	* before, checked byte by byte. Columns are the four grades ($gvar holds each table's grade
	* variable). In the students' table the third grade has its own questionnaire: vrow's third
	* argument names its variable when it differs (. = not measured in the third grade).
	*==========================================================================================*
	{
		*---------- helper: one variable = three lines (Mean, SE, Obs) x four grades ----------
		cap program drop vrow
		program define vrow
			args v lab g3
			if "`g3'" == "" local g3 `v'
			local Lm ""
			local Ls ""
			local Ln ""
			foreach g in 3 5 7 9 {
				local x = cond(`g' == 3, "`g3'", "`v'")
				if "`x'" == "." {
					local Lm "`Lm' &  &  & "
					local Ls "`Ls' &  &  & "
					local Ln "`Ln' &  &  & "
					continue
				}
				qui reg `x' if $gvar == `g' & resultado == 0, vce(cluster cd_escola)
				local mc  = _b[_cons]
				local scf = strtrim(string(_se[_cons],"%12.1f"))
				local Nc  = e(N)
				qui reg `x' if $gvar == `g' & resultado == 1, vce(cluster cd_escola)
				local mt  = _b[_cons]
				local stf = strtrim(string(_se[_cons],"%12.1f"))
				local Nt  = e(N)
				qui reg `x' resultado $estrato if $gvar == `g', vce(cluster cd_escola)
				local p   = 2*ttail(e(df_r), abs(_b[resultado]/_se[resultado]))
				local st  = cond(`p' < .01, "***", cond(`p' < .05, "**", cond(`p' < .1, "*", "")))
				local mcf = strtrim(string(`mc',"%12.1f"))
				local mtf = strtrim(string(`mt',"%12.1f"))
				local dff = strtrim(string(`mc' - `mt',"%12.1f"))
				local Lm `"`Lm' & `mcf' & `mtf' & `dff'`st'"'
				local Ls `"`Ls' & (`scf') & (`stf') & "'
				local Ln `"`Ln' & `Nc' & `Nt' & "'
			}
			file write tex `"`lab' & Mean`Lm' \\"' _n
			file write tex `" & SE`Ls' \\"' _n
			file write tex `" & Obs`Ln' \\"' _n
			file write tex "\addlinespace" _n
		end

		*---------- Table A.5: students ----------
		use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
		recode    fl_blank_score  (0 = 100) (1 = 0)				//100 = participated; response to the questionnaire
		recode    fl_blank_parent (0 = 100) (1 = 0)				//is conditional on having taken the assessment; in
		recode    fl_socio_blank  (0 = 100) (1 = 0)				//the 3rd grade it was answered by the legal
		replace   fl_blank_parent = . if fl_blank_score == 0	//guardians (fl_blank_parent)
		replace   fl_socio_blank  = . if fl_blank_score == 0
		foreach var in hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age ///
			resp_educ_1 resp_educ_2 resp_educ_3 mother_educ_1 mother_educ_2 mother_educ_3 gender color_white {
			replace `var' = `var'*100
		}
		global gvar cd_etapa_avaliada_turma

		file open  tex using "$textables/TableA5.tex", write replace
		file write tex "% Generated by Do files/2_Descriptives.do -- data rows only, do not edit by hand." _n
		file write tex "% The shell (caption, headers, notes, source) lives in Paper/Fin_Lit_Paper.tex." _n
		vrow fl_blank_score  "Participation: financial literacy assessment"
		vrow fl_socio_blank  "Response: socioeconomic questionnaire"							fl_blank_parent
		vrow hh_paved_street "Access to paved street"
		vrow hh_electri      "Access to electricity"
		vrow hh_piped_water  "Access to piped water"
		vrow hh_garb_col     "Access to garbage collection"
		vrow bolsa_fam       "Beneficiary of Bolsa Família"
		vrow adequate_age    "Adequate age for their grade"
		vrow mother_educ_1   "Mother education/Legal guardian: incomplete elementary school"	resp_educ_1
		vrow mother_educ_2   "Mother education/Legal guardian: incomplete high school"			resp_educ_2
		vrow mother_educ_3   "Mother education/Legal guardian: at least high school degree"	resp_educ_3
		vrow gender          "Gender: male"														.
		vrow color_white     "Color: white"														.
		file close tex

		*---------- Table A.6: teachers ----------
		use "$dtinter/Teacher's data_long.dta", clear
		keep if teacher_key_ != .
		foreach var in teacher_male teacher_age1 teacher_age2 teacher_age3 teacher_white ///
			d_teacher_expe1 d_teacher_expe2 d_teacher_expe3 wage_2 wage_3 wage_4 wage_5 {
			replace `var' = `var'*100
		}
		global gvar cd_etapa_aplicacao_turma

		file open  tex using "$textables/TableA6.tex", write replace
		file write tex "% Generated by Do files/2_Descriptives.do -- data rows only, do not edit by hand." _n
		file write tex "% The shell (caption, headers, notes, source) lives in Paper/Fin_Lit_Paper.tex." _n
		vrow teacher_male    "Gender: male"
		vrow teacher_age1    "Age: less than 35 years"
		vrow teacher_age2    "Age: 36 to 50 years"
		vrow teacher_age3    "Age: older than 51 years"
		vrow teacher_white   "Color: white"
		vrow d_teacher_expe1 "Experience: up to 5 years"
		vrow d_teacher_expe2 "Experience: 6 to 15 years"
		vrow d_teacher_expe3 "Experience: more than 16 years"
		vrow wage_2          "Wage: 3 to 4 minimum wages"
		vrow wage_3          "Wage: 4 to 5 minimum wages"
		vrow wage_4          "Wage: 5 to 6 minimum wages"
		vrow wage_5          "Wage: more than 6 minimum wages"
		file close tex

		display "BALANCE_TABLES_DONE"
	}


	**
	*==========================================================================================*
	* Table A.7 -- Pre-treatment balance test with administrative data at school level
	* (moved from the former 5f_Tables_PretBalance.do)
	*==========================================================================================*
*==========================================================================================*
* Generates the LaTeX fragment for the school-level pre-treatment balance table (Table A.7 in
* the paper; built from the 2_Descriptives.do "Table A10" block).
* One regression per public-record covariate: reg var resultado <strata>, cluster(group),
* run separately for Joinville (munic==42) and Manaus (munic==13). Beta = coef on treatment,
* Obs = N. Now with significance stars, straight from the code.
* Source data: Data/2. Intermediate/Treatment and Control Groups.dta (public school records).
* Output: Paper/tables/TableA7.tex  (\input by the appendix)
*==========================================================================================*


cap program drop starfmt
program define starfmt, rclass
	args b p
	local s = ""
	if `p' < 0.10 local s = "*"
	if `p' < 0.05 local s = "**"
	if `p' < 0.01 local s = "***"
	return local cell = string(`b',"%9.2f") + "`s'"
end

* variable list (same order as 2_Descriptives.do Table A10 block) and row labels
local vars DSU_F14 DSU_F58 TDI_F03 TDI_F05 TDI_F07 TDI_F09 ///
TA_F07_2009 TA_F09_2009 TA_F07_2011 TA_F09_2011 TA_F07_2013 TA_F09_2013 ///
TA_F03_2009 TA_F05_2009 TA_F03_2011 TA_F05_2011 TA_F03_2013 TA_F05_2013 ///
MAT_F09_2009 LP_F09_2009 MAT_F09_2011 LP_F09_2011 MAT_F09_2013 LP_F09_2013 ///
MAT_F05_2009 LP_F05_2009 MAT_F05_2011 LP_F05_2011 MAT_F05_2013 LP_F05_2013 ///
IDEB_F09_2009 IDEB_F09_2011 IDEB_F09_2013 IDEB_F05_2009 IDEB_F05_2011 IDEB_F05_2013

local labels `" "\% teachers in 1st to fifth grade with undergrad" "\% teachers in 6th to ninth grade with undergrad" "Age grade distortion third grade (2013)" "Age grade distortion fifth grade (2013)" "Age grade distortion seventh grade (2013)" "Age grade distortion ninth grade (2013)" "Grade-promotion seventh grade (2009)" "Grade-promotion ninth grade (2009)" "Grade-promotion seventh grade (2011)" "Grade-promotion ninth grade (2011)" "Grade-promotion seventh grade (2013)" "Grade-promotion ninth grade (2013)" "Grade-promotion third grade (2009)" "Grade-promotion fifth grade (2009)" "Grade-promotion third grade (2011)" "Grade-promotion fifth grade (2011)" "Grade-promotion third grade (2013)" "Grade-promotion fifth grade (2013)" "Math performance ninth grade (2009)" "Reading performance ninth grade (2009)" "Math performance ninth grade (2011)" "Reading performance ninth grade (2011)" "Math performance ninth grade (2013)" "Reading performance ninth grade (2013)" "Math performance fifth grade (2009)" "Reading performance fifth grade (2009)" "Math performance fifth grade (2011)" "Reading performance fifth grade (2011)" "Math performance fifth grade (2013)" "Reading performance fifth grade (2013)" "IDEB ninth grade (2009)" "IDEB ninth grade (2011)" "IDEB ninth grade (2013)" "IDEB fifth grade (2009)" "IDEB fifth grade (2011)" "IDEB fifth grade (2013)" "'

local nv : word count `vars'

* pooled control/treatment means, SEs, and strata-adjusted difference
tempname R
matrix R = J(`nv',8,.)     // 1 Nc 2 mc 3 sec 4 Nt 5 mt 6 set 7 diff(C-T) 8 pdiff

use "$dtinter/Treatment and Control Groups.dta", clear

local i = 0
foreach v of local vars {
	local ++i
	qui su `v' if resultado==0 & group!=.
	matrix R[`i',1]=r(N)
	matrix R[`i',2]=r(mean)
	if r(N)>0 matrix R[`i',3]=r(sd)/sqrt(r(N))
	qui su `v' if resultado==1 & group!=.
	matrix R[`i',4]=r(N)
	matrix R[`i',5]=r(mean)
	if r(N)>0 matrix R[`i',6]=r(sd)/sqrt(r(N))
	*Same statistic as Tables A.2, A.5 and A.6: the reported difference is the raw control-treatment
	*gap in means, and the strata dummies and the clusters enter only the test behind the stars.
	*Here the cluster is the randomization group, since each school is a single observation.
	capture reg `v' resultado $estrato if group!=., vce(cluster group)
	if _rc==0 {
		matrix R[`i',7] = R[`i',2] - R[`i',5]
		matrix R[`i',8] = 2*ttail(e(df_r), abs(_b[resultado]/_se[resultado]))
	}
}

*==========================================================================================*
* Write the LaTeX fragment
*==========================================================================================*
file open tex using "$textables/TableA7.tex", write replace
file write tex "% Generated by Do files/2_Descriptives.do (pre-treatment balance block) -- data rows only, do not edit by hand." _n

forvalues r = 1/`nv' {
	local lab : word `r' of `labels'
	file write tex "`lab'"
	file write tex " & " (strtrim(string(R[`r',1],"%9.0f"))) " & " (string(R[`r',2],"%9.2f"))
	file write tex " & " (strtrim(string(R[`r',4],"%9.0f"))) " & " (string(R[`r',5],"%9.2f"))
	if missing(R[`r',7]) file write tex " & \\" _n
	else {
		starfmt `=R[`r',7]' `=R[`r',8]'
		file write tex " & `r(cell)' \\" _n
	}
	file write tex " & & (" (string(R[`r',3],"%9.2f")) ")"
	file write tex " & & (" (string(R[`r',6],"%9.2f")) ") & \\" _n
}

file close tex

display "PRETBALANCE_TABLE_DONE"


	*======================================================================================================================*
	*NOT USED IN THE PAPER -- kept for reference only, commented out.
	*Legacy Excel exports whose numbering predates the current paper, exploratory blocks, the
	*IDEB-vs-proficiency scatter plots, and the superseded first writer of Table A.2.
	*======================================================================================================================*
/*

	**
	*Figures B1a B1b ok
	*---------------------------------------------------------------------------------------------------------------------*
	{	//correlation between financial proficiency and the IDEB (Education Development Index. )
		use 	"$dtfinal/Fin_Lit_pooled_data_clean.dta",replace 
			merge 	m:1 cd_escola using  "$dtinter/Treatment and control groups.dta", nogen  

			collapse (mean)vl_proficiencia IDEB_F05_2015 IDEB_F09_2015 if serie == 5 | serie == 9, by(serie cd_escola)
			
					twoway ///
					(lfit   vl_proficiencia IDEB_F05_2015 if serie == 5, lp(shortdash) lcolor(cranberry) lw(thick)) 	///
				|| (scatter vl_proficiencia IDEB_F05_2015 if serie == 5, symbol(O) color(emidblue*0.8)  msize(medsmall) mlabcolor(black) mlabposition(9) mlabsize(2)	 ///   
					ylabel(,nogrid) 																					///
					title("", size(medium) color(black)) 																///
					ytitle("Financial Proficiency Score, 2015", size(medium) color(black)) 								///
					xtitle("IDEB of fifth graders, 2015", size(medium)) ///
					graphregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white))	///
					plotregion( color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) 	///
					ysize(5) xsize(7)							 														///
					legend(off) ///
					note("", span color(black) fcolor(background) pos(7) size(small)))
					graph export "$figures/FigureIDEB_grade5.pdf", as(pdf) replace	

						twoway ///
					(lfit   vl_proficiencia IDEB_F09_2015 if serie == 9, lp(shortdash) lcolor(cranberry) lw(thick)) 	///
				|| (scatter vl_proficiencia IDEB_F09_2015 if serie == 9, symbol(O) color(emidblue*0.8)  msize(medsmall) mlabcolor(black) mlabposition(9) mlabsize(2)	 ///   
					ylabel(,nogrid) 																					///
					title("", size(medium) color(black)) 																///
					ytitle("Financial Proficiency Score, 2015", size(medium) color(black)) 								///
					xtitle("IDEB of ninth graders, 2015", size(medium)) ///
					graphregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white))	///
					plotregion( color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) 	///
					ysize(5) xsize(7)							 														///
					legend(off) ///
					note("", span color(black) fcolor(background) pos(7) size(small)))
					graph export "$figures/FigureIDEB_grade9.pdf", as(pdf) replace	
	}
	
		
	**
	*Table A2
	*---------------------------------------------------------------------------------------------------------------------*
	{	//sample selected
		use 	"$dtinter/Treatment and Control Groups.dta", clear
			label 	 define			 tipo 1 "Only initial grades" 2 "Only final grades" 3 "Initial and final grades"
			label 	 val  	 tipo_escola tipo 
			gen 	 id = 1
			collapse (sum)id, by(resultado tipo_escola munic)
			expand 	 2, gen(REP)
			decode 	 munic, gen(mun)
			replace  mun = "Total" if REP == 1
			collapse (sum) id, by(resultado tipo_escola mun)
			reshape  wide id, i(resultado tipo_escola) j(mun) string
			reshape  wide id*, i(tipo_escola) j(resultado)
			foreach city in Joinville Manaus Total {
				egen id`city' = rowtotal(id`city'*)
			}
			gen 	idManaus_censo = .
			replace idManaus_censo = 202 if tipo_escola == 1 		//numero de escolas de acordo com o Censo Escolar 
			replace idManaus_censo = 35  if tipo_escola == 2
			replace idManaus_censo = 65  if tipo_escola == 3
			order    tipo_escola idJoinville idJoinville1 idJoinville0 idManaus_censo  idManaus idManaus1 idManaus0 idTotal1
			expand 2, gen(REP)
			replace tipo_escola = 0 if REP == 1
			collapse (sum)id*, by(tipo_escola)
			tostring*, replace force
			replace tipo_escola = "1st-5th grades" in 2
			replace tipo_escola = "6th-9th grades" in 3
			replace tipo_escola = "1st-9th grades" in 4 
			replace tipo_escola = "Total" in 1
			gen coladd = "All"
			gen coladd2 = ""
			gen coladd3 = ""
			order tipo_escola idJoinville coladd idJoinville1 idJoinville0 coladd2 idManaus* coladd3
			replace idManaus = "36 sampled based on 2013 IDEB 1st-5th grades" in 2
			replace idManaus = "28 sampled based on 2013 IDEB 6th-9th grades" in 3
			replace idManaus = "All" in 4
			set obs 8
			drop idTotal
			replace tipo_escola 		= "Schools offering" in 5
			replace idJoinville 		= "Joinville" in 6
			replace idManaus_censo 		= "Manaus" in 6
			replace idTotal1 			= "Manaus and Joinville" in 6
			replace idJoinville 		= "Number of schools" in 7
			replace coladd 				= "Randomization sample" in 7
			replace idJoinville1 		= "Randomization Groups" in 7
			replace idJoinville1 		= "Treatment" in 8
			replace idJoinville0 		= "Control" in 8 
			replace idManaus_censo 		= "Number of schools" in 7
			replace idManaus			= "Randomization sample" in 7
			replace idManaus1 			= "Randomization Groups" in 7
			replace idManaus1			= "Treatment" in 8
			replace idManaus0 			= "Control" in 8 
			replace idTotal1 			= "Number of randomized schools" in 7
			replace idTotal1 			= "Treatment" in 8
			replace idTotal0 			= "Control" in 8
			gen 	order = 1 in 6
			replace order = 2 in 7
			replace order = 3 in 8
			replace order = 4 in 5
			replace order = 5 in 2
			replace order = 6 in 3
			replace order = 7 in 4
			replace order = 8 in 1		
		
			sort order
			drop order
			export excel "$descriptives/Table A2.xlsx", firstrow(variables) replace
	}
	
	
	**
	**Table A4
	*---------------------------------------------------------------------------------------------------------------------*
	{
		clear
		set obs 30
		gen 	col1 = "Statement"  															in 1
		gen 	col2 = "Answers' scale" 														in 1
		replace col2 = "Totally agree" 															in 2
		gen 	col3 = "Agree" 																	in 2
		gen 	col4 = "Disagree" 																in 2
		gen 	col5 = "Totally disagree" 														in 2
		gen 	col6 = "Weight in index" 														in 1
		
		
		replace col1 = "Consumption questions" 													in 3
		
		replace col1 = "I buy what I want, then I see how I can pay" 							in 4
		replace col6 = "0.45" in 4
		
		replace col1 = "I see no problem in owing money"										in 5
		replace col6 = "0.44" in 5
		
		replace col1 = "If the brand is famous the product is of high quality" 					in 6
		replace col6 = "0.32" in 6

		replace col1 = "The best product is always the most expensive" 							in 7
		replace col6 = "0.33" in 7

		replace col1 = "I plan before spending my money" 										in 8
		replace col6 = "0.1" in 8

		replace col1 = "It is worthless to plan because the money comes from luck" 				in 9
		replace col6 = "0.43" in 9	

		replace col1 = "Buy what I want is more important than have planning" 					in 10
		replace col6 = "0.45" in 10

		replace col1 = "Saving questions"														in 12
		
		replace col1 = "I think that saving money is important to avoid problems in the future"	in 13
		replace col6 = "0.41" in 13

		replace col1 = "I feel safer when I can save some money"								in 14
		replace col6 = "0.39" in 14
		
		replace col1 = "Saving some money is important to avoid debt"							in 15
		replace col6 = "0.42" in 15

		replace col1 = "Buying everything I want is more important than putting the money together"	in 16
		replace col6 = "0.24" in 16

		replace col1 = "Avoiding waste is also a way to save money"								in 17
		replace col6 = "0.38" in 17

		replace col1 = "I try to use the products for longer"									in 18
		replace col6 = "0.35" in 18

		replace col1 = "Whenever I can, I save money"											in 19
		replace col6 = "0.37" in 19
		
		replace col1 = "I would rather spend the change on something I want than save the money for later"	in 20
		replace col6 = "0.19" in 20

		foreach row in 4 5 6 7 9 10 16 20 {
			replace col2 = "1" in `row'
			replace col3 = "2" in `row'
			replace col4 = "3" in `row'
			replace col5 = "4" in `row'
		}
		
		foreach row in 8 13 14 15 17 18 19 {
			replace col2 = "4" in `row'
			replace col3 = "3" in `row'
			replace col4 = "2" in `row'
			replace col5 = "1" in `row'
		}	
		export excel "$descriptives/Table A4.xlsx", replace	
	}

	
	**
	**Table A5 ok
	*---------------------------------------------------------------------------------------------------------------------*
	{
		**
		*block 1
		*-----------------------------------------------------------------------------------------------------------------*
		{	
		
			*Students' participation rate
			*-----------------------------------------------------------------------------------------------------------------*
				use  "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
				
				recode    fl_blank_score (0 = 100) (1 = 0)		//100 if student answered the financial literacy questionnaire, 0 if the student did not answer
				label var fl_blank_score  "Students' participation rate"
			

			*Response rate of socieconomic and attitudinal questionnaires
			*-----------------------------------------------------------------------------------------------------------------*
				recode    fl_blank_parent (0 = 100) (1 = 0)
				recode    fl_socio_blank  (0 = 100) (1 = 0)
				replace   fl_blank_parent = . if fl_blank_score == 0 
				replace   fl_socio_blank  = . if fl_blank_score == 0 
				label var fl_blank_parent "Response rate of socioeconomic and attitudinal questionnaires"
				label var fl_socio_blank  "Response rate of socioeconomic and attitudinal questionnaires"	  
			
			*Balance test
			*-----------------------------------------------------------------------------------------------------------------*
			
			
			
				* Run balance tests
				iebaltab fl_blank_score  fl_blank_parent if cd_etapa_aplicacao_turma == 3, format(%12.1f)  cov(estrato) rowvarlabels grpvar(resultado) save("$descriptives/Table_block1_3grade.xlsx") replace
				iebaltab fl_blank_score  fl_socio_blank  if cd_etapa_aplicacao_turma == 5, format(%12.1f)  cov(estrato) rowvarlabels grpvar(resultado) save("$descriptives/Table_block1_5grade.xlsx") replace
				iebaltab fl_blank_score  fl_socio_blank  if cd_etapa_aplicacao_turma == 7, format(%12.1f)  cov(estrato) rowvarlabels grpvar(resultado) save("$descriptives/Table_block1_7grade.xlsx") replace
				iebaltab fl_blank_score  fl_socio_blank  if cd_etapa_aplicacao_turma == 9, format(%12.1f)  cov(estrato) rowvarlabels grpvar(resultado) save("$descriptives/Table_block1_9grade.xlsx") replace
			
			
			
			*Organizing
			*-----------------------------------------------------------------------------------------------------------------*
				foreach grade in 3 5 7 9 {
					import 		excel "$descriptives\Table_block1_`grade'grade.xlsx", allstring clear
						foreach var of varlist * {
							replace `var' ="" if inlist(`var', "Variable", "N", "Mean/SE", "(1)-(2)")
						}
						if `grade' == 3 replace C = "Third-grade"   in 1
						if `grade' == 5 replace C = "Fifth-grade"   in 1
						if `grade' == 7 replace C = "Seventh-grade" in 1
						if `grade' == 9 replace C = "Ninth-grade"   in 1
						replace 	C = "C" in 2
						replace 	E = "T" in 2
						replace 	F = "T-C" in 2
						replace 	A = A[_n-1] if A == ""
						gen 		obs = _n
						egen 		group = group(A)
						gen 		obs_group = 1 		if					 		!missing(group)
						replace 	obs_group = 2 		if group[_n] == group[_n-1] & !missing(group)
						expand 		3 					if obs_group == 2, gen(REP)
						sort 		obs A REP 
						replace 	C = B[_n-2] 		if REP == 1
						replace 	E = D[_n-2] 		if REP == 1
						replace 	E = "" in 1 
						replace 	F = "" in 1
						drop in 12/14
						gen 	    variable = "Mean" 	if obs_group == 1 												& !missing(group)	
						replace	    variable = "SE"	  	if obs_group == 2 & obs_group[_n-1] == 1							& !missing(group)
						replace	    variable = "OBS"  	if obs_group == 2 & obs_group[_n-1] == 2 & obs_group[_n+1] == 2	& !missing(group)
						order   	A variable
						drop 		B D obs group obs_group REP
						replace 	A = "" 				if A[_n] == A[_n-1] | A[_n] == A[_n-2]
						replace 	A = "" 				if A[_n] == A[_n-1] | A[_n] == A[_n-3]
						replace 	variable = A[_n+1] 	if A[_n+1] != ""
						drop 		A
						if 		`grade' > 3 drop variable			
						if 		`grade' == 3		export	 excel using "$descriptives\Table A5.xls",  replace
						if 		`grade' == 5 		export	 excel using "$descriptives\Table A5.xls",  sheetmodify cell(E1)	
						if 		`grade' == 7 		export	 excel using "$descriptives\Table A5.xls",  sheetmodify cell(H1)	
						if 		`grade' == 9 		export	 excel using "$descriptives\Table A5.xls",  sheetmodify cell(K1)	
						erase 	"$descriptives\Table_block1_`grade'grade.xlsx"
				}
		}
		
		
		**
		*block 2
		*-----------------------------------------------------------------------------------------------------------------*
		{	
			
			*When the textbook was received
			*-----------------------------------------------------------------------------------------------------------------*
				use  "$dtfinal/Fin_Lit_pooled_data_clean.dta",clear 
				
				bys d: tab socio_rp_61 cd_etapa_aplicacao_turma, mis
				
				tab 	socio_rp_61, gen (d_when_receive)
				tab 	cd_etapa_aplicacao_turma if resultado == 1 & fl_blank_score == 0 //numero de estudantes tratados em cada serie e que participaram da prova

				foreach var of varlist d_when*{
					replace `var' = 100 if `var' == 1
				}

				keep if resultado == 1
				*-----------------------------------------------------------------------------------------------------------------*
				sumstats (d_when_receive1 d_when_receive2 d_when_receive3 d_when_receive4 if resultado == 1 & cd_etapa_aplicacao_turma == 5) ///
						 (d_when_receive1 d_when_receive2 d_when_receive3 d_when_receive4 if resultado == 1 & cd_etapa_aplicacao_turma == 7) ///
						 (d_when_receive1 d_when_receive2 d_when_receive3 d_when_receive4 if resultado == 1 & cd_etapa_aplicacao_turma == 9) ///
				using "$descriptives/Table_block2.xlsx", replace stats(N mean sd)

			*Organizing
			*-----------------------------------------------------------------------------------------------------------------*
				import 		excel "$descriptives\Table_block2.xlsx", allstring clear
				drop 		in 1
				destring, 	replace
				gen 		obs = _n
				mkmat 		B C D if inrange(obs,2,5  ), matrix(A1)
				mkmat 		B C D if inrange(obs,8,11 ), matrix(A2)
				mkmat 		B C D if inrange(obs,14,17), matrix(A3)
				matrix 		T = (A1 , A2,  A3)
				clear 
				svmat 		T
				gen 		des	=  "Beginning of the year" 		in 1
				replace 	des	= "By the middle of the year" 	in 2
				replace 	des	= "In the end of the year" 		in 3
				replace 	des	= "Haven’t received" 			in 4
				order des
				tostring *, replace force
				replace 	T1 = ""
				replace 	T4 = ""
				replace 	T7 = ""
				set 		obs 6
				gen 		obs = _n
				gsort 	   -obs
				replace  des = "Deliver of the financial education textbooks according to students, in %" in 1
				foreach var in T2 T5 T8 {
					replace `var' = "Mean" in 2
					replace `var' = substr(`var',1, 4) if `var' != "Mean"
				}
				foreach var in T3 T6 T9 {
					replace `var' = "SD" in 2
					replace `var' = substr(`var',1, 4) if `var' != "Mean"& `var' != "SD"
				}
				gen 		T10 =.
				gen 		T11=.
				order 	des T10 T11
				drop 	obs
				
				export	 excel using "$descriptives\Table A5.xls",  sheetmodify cell(A12)
				erase 	"$descriptives\Table_block2.xlsx"
		}
			

		**
		**block 3
		*-----------------------------------------------------------------------------------------------------------------*
		{
			*Semester in which teachers used the teaching material, % of the textbook covered
			*-----------------------------------------------------------------------------------------------------------------*
				
				**
				*Teacher Data
				*-------------------------------------------------------------------------------------------------------------*
				use 	"$dtinter/Teacher's data.dta", clear				//Teacher's dataset to have one teacher observation per row
				rename (prof1_rp_* prof2_rp_* prof3_rp_*) (prof_rp_*_1 prof_rp_*_2 prof_rp_*_3)
				rename (teacher*_key cd_disciplina_prof*) (teacher_key_* cd_disciplina_prof_*)  
				keep 	prof_* teacher_* cd_disciplina* cd_turma
				reshape long teacher_key_ cd_disciplina_prof_  prof_rp_01_ prof_rp_02_ prof_rp_03_ prof_rp_04_ ///
						 prof_rp_05_ prof_rp_06_ prof_rp_07_ prof_rp_08_ prof_rp_09_ prof_rp_10_ prof_rp_11_ prof_rp_12_ prof_rp_13_ prof_rp_14_ prof_rp_15_ ///
						 prof_rp_16_ prof_rp_17_ prof_rp_18_ prof_rp_19_ prof_rp_20_ prof_rp_21_ prof_rp_22_ prof_rp_23_ prof_rp_24_ prof_rp_25_ prof_rp_26_ ///
						 prof_rp_27_ prof_rp_28_ prof_rp_29_ prof_rp_30_ prof_rp_31_ prof_rp_32_ prof_rp_33_ prof_rp_34_ prof_rp_35_ prof_rp_36_ prof_rp_37_  ///
						 prof_rp_38_ prof_rp_39_ prof_rp_40_ prof_rp_41_ prof_rp_42_ prof_rp_43_ prof_rp_44_ prof_rp_45_ prof_rp_46_ prof_rp_47_ prof_rp_48_  ///
						 prof_rp_49_ prof_rp_50_ prof_rp_51_ prof_rp_52_ prof_rp_53_ prof_rp_54_ prof_rp_55_ prof_rp_56_ prof_rp_57_ prof_rp_58_ prof_rp_59_  ///
						 prof_rp_60_ prof_rp_61_ prof_rp_62_ prof_rp_63_ prof_rp_64_ prof_rp_65_ ///
						 , i(cd_turma) j (prof)
						sort cd_turma prof
						drop if missing(teacher_key_)
						bys cd_turma: gen t = _N		//t is the number of teachers in that classroom
											
						*
						*Keeping only if there is only one teacher in the classroom or if there is more than one teacher but the answer to the question % of the syllabus covered is different than missing.
						keep if (t == 1 ) | (t > 1 & !missing(prof_rp_40_))  //when there is only one teacher in the class or when its more than one teacher keep the one that it is not missing. 
						drop t
						bys  cd_turma: gen t = _N
						keep if (t == 1 ) | (t > 1 & !missing(prof_rp_39_))  
						drop t
						bys     cd_turma: gen t = _N
						sort    cd_turma  prof
						br      cd_turma  prof t prof_rp_40_  prof_rp_39_ 
						gsort   cd_turma 	   - prof_rp_40_ -prof_rp_39_
						egen    cd_turmatag = tag(cd_turma)
						keep if cd_turmatag == 1 //keeping only one teacher per class
						drop t  cd_turmatag
						
				tempfile prof
				save 	`prof'

				
				**
				**Student Data
				*-------------------------------------------------------------------------------------------------------------*
				use  	"$dtfinal/Fin_Lit_pooled_data_clean.dta",clear 	//organized at classroom level
				
				**
				*Imperfect complience
				preserve
					merge 	m:1 		cd_turma 		using `prof' , keep(1 3) nogen
					bys resultado: tab socio_rp_61 prof_rp_40_ if cd_etapa_aplicacao_turma != 3, mis
				restore
				
				**
				*Merging teacher data with classroom information
				egen 	tag_turma = tag(cd_turma)
				keep if tag_turma == 1 
				keep 	cd_estado cd_municipio cd_localizacao_escola cd_escola cd_turma cd_etapa_aplicacao_turma estrato strata421 strata422 strata423 strata131 strata132 strata133 resultado 
				merge 	1:1 		cd_turma 		using `prof' , keep(1 3) nogen

				**
				*Semester in which they used the material
				gen     semester=1 if (prof_rp_39_==1 | prof_rp_39_==2 | prof_rp_39_==3) 	
				replace semester=2 if (prof_rp_39_==4 | prof_rp_39_==5 | prof_rp_39_==6) 	
				replace semester=3 if (prof_rp_39_==7) 										
				tab	 	semester, gen (d_semester)
			
				**
				*Percentage of syllabus covered
				tab prof_rp_40_, gen (d_content)
				foreach var of varlist d_semester* d_content* {
					replace `var' = 100 if `var' == 1
				}
				
				**
				**Statistics
				keep if resultado == 1
				*-----------------------------------------------------------------------------------------------------------------*
				sumstats (d_semester1  d_semester2  d_semester3 d_content1 d_content2 d_content3 d_content4 if cd_etapa_aplicacao_turma == 3) ///
						 (d_semester1  d_semester2  d_semester3 d_content1 d_content2 d_content3 d_content4 if cd_etapa_aplicacao_turma == 5) ///
						 (d_semester1  d_semester2  d_semester3 d_content1 d_content2 d_content3 d_content4 if cd_etapa_aplicacao_turma == 7) ///
						 (d_semester1  d_semester2  d_semester3 d_content1 d_content2 d_content3 d_content4 if cd_etapa_aplicacao_turma == 9) ///
				using "$descriptives/Table_block3.xlsx", stats(N mean sd) replace
				
						
				**
				**Organizing
				*-----------------------------------------------------------------------------------------------------------------*
					import 		excel "$descriptives\Table_block3.xlsx", allstring clear
					drop 		in 1
					destring, 	replace
					gen 		obs = _n
					mkmat 		B C D if inrange(obs,2,8  ), matrix(A1)
					mkmat 		B C D if inrange(obs,11,17), matrix(A2)
					mkmat 		B C D if inrange(obs,20,26), matrix(A3)
					mkmat 		B C D if inrange(obs,29,35), matrix(A4)
					matrix T = (A1 , A2,  A3, A4)
					clear 
					svmat T
					set obs 11
					tostring *, replace force
					gen 	dec = "Only in 1st semester" in 1
					replace dec = "Only in 2nd semester" in 2
					replace dec = "All year" in 3
					replace dec = "Less than 40%" in 4
					replace dec = "Between 40% and 60%" in 5
					replace dec = "Between 60% and 80%" in 6
					replace dec = "More than 80%" in 7
					order dec
					foreach var of varlist T1 T4 T7 T10 {
						replace `var' = ""
					}
					replace dec = "% of classes by the semester in which the teachers used the financial education textbooks" in 8
					replace dec = "% of classes by the percentage of the financial literacy textbook covered by the teachers" in 10
					gen 	order = 1 in 8
					replace order = 2 in 9
					replace order = 3 in 1
					replace order = 4 in 2
					replace order = 5 in 3
					replace order = 6 in 10
					replace order = 7 in 11
					replace order = 8 in 4
					replace order = 9  in 5
					replace order = 10 in 6
					replace order = 11 in 7
					
					
					sort order
					foreach var in T2 T5 T8 T11 {
						replace `var' = "Mean" in 2
						replace `var' = "Mean" in 7
						replace `var' = substr(`var',1, 4) if `var' != "Mean"
					}
					foreach var in T3 T6 T9 T12 {
						replace `var' = "SD" in 2
						replace `var' = "SD" in 7
						replace `var' = substr(`var',1, 4) if `var' != "Mean"& `var' != "SD"
					}
					drop order T1
					export	 excel using "$descriptives\Table A5.xls",  sheetmodify cell(A19)	
					erase 	"$descriptives\Table_block3.xlsx"
		}
	}
	

	**
	*Table A6
	*---------------------------------------------------------------------------------------------------------------------*	
	{	//teachers

			foreach grade in 3 5 7 9 {
				
			use  "$dtinter/Teacher's data_long.dta",replace 

			keep if teacher_key_!= . 

			local variables teacher_male teacher_age1 teacher_age2 teacher_age3 teacher_white d_teacher_expe1 d_teacher_expe2 d_teacher_expe3  wage_2 wage_3 wage_4 wage_5
			
			estimates clear

				foreach var of local variables {
					replace `var' = `var'*100 if cd_etapa_aplicacao_turma == `grade'
				}
				
				label var teacher_male  		"Gender: male"
				label var teacher_age1			"Age: less than 35 yers"
				label var teacher_age2  		"Age: 36 to 50 yers"
				label var teacher_age3 			"Age: older than 51 years"
				label var teacher_white 		"Color: white"
				label var d_teacher_expe1 		"Experience: up to 5 years"
				label var d_teacher_expe2 		"Experience: 6 to 15 years"
				label var d_teacher_expe3  		"Experience: more than 16 years"
				label var wage_2 				"Wage: 3 to 4 minimum wages"
				label var wage_3 				"Wage: 4 to 5 minimum wages"
				label var wage_4 				"Wage: 5 to 6 minimum wages"
				label var wage_5				"Wage: more than 6 minimum wages"
				
				**
				*Balance test I
				*-------------------------------------------------------------------------------------------------------------*
				iebaltab `variables' if cd_etapa_aplicacao_turma == `grade', cov($estrato) format(%12.1f)  grpvar(resultado) save("$descriptives/Table6_`grade' grade.xlsx") rowvarlabels replace

				/*
				**
				*Balance test II
				*Regression of the covariates on the treatment dummy adding strata as control and including % of missings in the table
				*-------------------------------------------------------------------------------------------------------------*
				foreach var in `variables' {
					
					count if `var' == . & cd_etapa_aplicacao_turma == `grade' & resultado == 1 
					local miss_trat = r(N)
					
					count if `var' == . & cd_etapa_aplicacao_turma == `grade' & resultado == 0 
					local miss_cont = r(N)
					
					count if 			  cd_etapa_aplicacao_turma == `grade' & resultado == 1 
					local n_trat = r(N)
					
					count if 			  cd_etapa_aplicacao_turma == `grade' & resultado == 0 
					local n_cont = r(N)
					
					reg `var' resultado $estrato if cd_etapa_aplicacao_turma == `grade', coefleg cluster(cd_escola) 
					est store res_`var'
					if `grade' == 3 outreg2 * using "$descriptives/Balance test II for teachers_3grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2) 
					if `grade' == 5 outreg2 * using "$descriptives/Balance test II for teachers_5grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)
					if `grade' == 7 outreg2 * using "$descriptives/Balance test II for teachers_7grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)  
					if `grade' == 9 outreg2 * using "$descriptives/Balance test II for teachers_9grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)
				}
				*/
			
				**
				*Setting up the table
				*-------------------------------------------------------------------------------------------------------------*
					import 		excel "$descriptives\Table6_`grade' grade.xlsx", allstring clear
					replace 	A = A[_n-1] if A == ""
					gen 		obs = _n
					egen 		group = group(A)
					gen 		obs_group = 1
					replace 	obs_group = 2 if group[_n] == group[_n-1]
					expand 		3 if obs_group == 2, gen(REP)
					sort 		obs A REP 
					replace 	C = B[_n-2] if REP == 1
					replace 	E = D[_n-2] if REP == 1
					replace 	C = "C" in 2
					replace 	E = "T" in 2
					replace 	F = "T-C" in 2
					replace 	E = "" in 1 
					replace 	F = "" in 1
					drop 		in 3/6
					gen 	    variable = "Mean" if obs_group == 1 & obs_group[_n-1] == 1
					replace	    variable = "SE"	  if obs_group == 2 & obs_group[_n-1] == 1
					replace	    variable = "OBS"  if obs_group == 2 & obs_group[_n-1] == 2 & obs_group[_n+1] == 2
					drop 		B D obs group obs_group REP
					replace 	A = "" if A[_n] == A[_n-1] | A[_n] == A[_n-2]
					replace 	A = "" if A[_n] == A[_n-1] | A[_n] == A[_n-3]
					order A variable
					if `grade' > 3 drop A 	variable		
					if `grade' == 3 replace C = "Third-grade"   in 1
					if `grade' == 5 replace C = "Fifth-grade"   in 1
					if `grade' == 7 replace C = "Seventh-grade" in 1
					if `grade' == 9 replace C = "Ninth-grade"   in 1
					if `grade' == 3		export	 excel using "$descriptives\Table A6.xls",  replace
					if `grade' == 5 	export	 excel using "$descriptives\Table A6.xls",  sheetmodify cell(F1)	
					if `grade' == 7 	export	 excel using "$descriptives\Table A6.xls",  sheetmodify cell(I1)	
					if `grade' == 9 	export	 excel using "$descriptives\Table A6.xls",  sheetmodify cell(L1)	
					erase "$descriptives\Table6_`grade' grade.xlsx"
			}
		}	

		
	**
	*Table A7
	*---------------------------------------------------------------------------------------------------------------------*	
	{	//students

			foreach grade in 3 5 7 9 {
				
				use  "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear

				estimates clear

				if `grade' == 3 local variables hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age resp_educ_1   resp_educ_2   resp_educ_3  
				
				if `grade' != 3 local variables hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age mother_educ_1 mother_educ_2 mother_educ_3 gender color_white
				
				foreach var of local variables {
					replace `var' = `var'*100 if cd_etapa_avaliada_turma == `grade'
				}
				
				**
				*Balance test I
				*-------------------------------------------------------------------------------------------------------------*
				iebaltab `variables' if cd_etapa_avaliada_turma == `grade',  cov(estrato)  format(%12.1f)   grpvar(resultado) save("$descriptives/Table7_`grade' grade.xlsx") rowvarlabels replace
			
				/*
				**
				*Balance test II
				*Regression of the covariates on the treatment dummy adding strata as control and including % of missings in the table
				*-------------------------------------------------------------------------------------------------------------*
				foreach var in `variables' {
					
					count if `var' == . & cd_etapa_avaliada_turma == `grade' & resultado == 1 & (fl_socio_blank==0 | fl_blank_parent==0) 
					local miss_trat = r(N) 	//missing observations among treated students

					count if `var' == . & cd_etapa_avaliada_turma == `grade' & resultado == 0 & (fl_socio_blank==0 | fl_blank_parent==0)
					local miss_cont = r(N)	//missing observations among control
					
					count if 			  cd_etapa_avaliada_turma == `grade' & resultado == 1 & (fl_socio_blank==0 | fl_blank_parent==0)   
					local n_trat = r(N)		//total oftreated observations 
					
					count if 			  cd_etapa_avaliada_turma == `grade' & resultado == 0 & (fl_socio_blank==0 | fl_blank_parent==0) 
					local n_cont = r(N)		//total of control observations
					
					reg `var' resultado $estrato if cd_etapa_avaliada_turma == `grade' & (fl_socio_blank==0 | fl_blank_parent==0), coefleg 		  cluster(cd_escola) 
					est store res_`var'
					
					if `grade' == 3 outreg2 * using "$descriptives/Balance test II for students_3grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2) 
					if `grade' == 5 outreg2 * using "$descriptives/Balance test II for students_5grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)
					if `grade' == 7 outreg2 * using "$descriptives/Balance test II for students_7grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)  
					if `grade' == 9 outreg2 * using "$descriptives/Balance test II for students_9grade.xls", append label addstat("Missing tratados", `miss_trat'			, "Missing controles",`miss_cont', "Number treat", `n_trat', "Number control", `n_cont') bdec(2) sdec(2)
				}
				*/

				
				**
				*Setting up the table
				*-------------------------------------------------------------------------------------------------------------*
					import 		excel "$descriptives\Table7_`grade' grade.xlsx", allstring clear
					replace 	A = A[_n-1] if A == ""
					gen 		obs = _n
					egen 		group = group(A)
					gen 		obs_group = 1
					replace 	obs_group = 2 if group[_n] == group[_n-1]
					expand 		3 if obs_group == 2, gen(REP)
					sort 		obs A REP 
					replace 	C = B[_n-2] if REP == 1
					replace 	E = D[_n-2] if REP == 1
					replace 	C = "C" in 2
					replace 	E = "T" in 2
					replace 	F = "T-C" in 2
					replace 	E = "" in 1 
					replace 	F = "" in 1
					drop 		in 3/6
					gen 	    variable = "Mean" if obs_group == 1 & obs_group[_n-1] == 1
					replace	    variable = "SE"	  if obs_group == 2 & obs_group[_n-1] == 1
					replace	    variable = "OBS"  if obs_group == 2 & obs_group[_n-1] == 2 & obs_group[_n+1] == 2
					drop 		B D obs group obs_group REP
					replace 	A = "" if A[_n] == A[_n-1] | A[_n] == A[_n-2]
					replace 	A = "" if A[_n] == A[_n-1] | A[_n] == A[_n-3]
					order A variable
					if `grade' > 3 drop A 	variable		
					if `grade' == 3 replace C = "Third-grade"   in 1
					if `grade' == 5 replace C = "Fifth-grade"   in 1
					if `grade' == 7 replace C = "Seventh-grade" in 1
					if `grade' == 9 replace C = "Ninth-grade"   in 1
					if `grade' == 3		export	 excel using "$descriptives\Table A7.xls",  replace
					if `grade' == 5 	export	 excel using "$descriptives\Table A7.xls",  sheetmodify cell(F1)	
					if `grade' == 7 	export	 excel using "$descriptives\Table A7.xls",  sheetmodify cell(I1)	
					if `grade' == 9 	export	 excel using "$descriptives\Table A7.xls",  sheetmodify cell(L1)	
					erase "$descriptives\Table7_`grade' grade.xlsx"

			}
		}
		
		
	**
	**Table A10
	*---------------------------------------------------------------------------------------------------------------------*
	{
		use "$dtinter/Treatment and Control Groups.dta", clear
		
		**
		*Schools in Joinville
		*-----------------------------------------------------------------------------------------------------------------*
		estimates clear
		foreach var in  DSU_F14 DSU_F58 TDI_F03 TDI_F05 TDI_F07 TDI_F09 			///
		TA_F07_2009 TA_F09_2009 TA_F07_2011 TA_F09_2011 TA_F07_2013 TA_F09_2013 	///
		TA_F03_2009 TA_F05_2009 TA_F03_2011 TA_F05_2011 TA_F03_2013 TA_F05_2013 	///
		MAT_F09_2009 LP_F09_2009 MAT_F09_2011 LP_F09_2011 MAT_F09_2013 LP_F09_2013  ///
		MAT_F05_2009 LP_F05_2009 MAT_F05_2011 LP_F05_2011 MAT_F05_2013 LP_F05_2013 	///
		IDEB_F09_2009 IDEB_F09_2011 IDEB_F09_2013 									///
		IDEB_F05_2009 IDEB_F05_2011 IDEB_F05_2013 {
			eststo: reg `var' resultado $estrato if  group!=. & munic == 42 ,  vce(cluster group)  
		}	
		global regressions*
		outreg2 [$regressions] using "$descriptives/Balance test for schools_Joinville.xls", nor nocons tstat  dec(2) noparen replace
		
		**
		*Schools in Manaus
		*-----------------------------------------------------------------------------------------------------------------*
		estimates clear
		foreach var in  DSU_F14 DSU_F58 TDI_F03 TDI_F05 TDI_F07 TDI_F09 			///
		TA_F07_2009 TA_F09_2009 TA_F07_2011 TA_F09_2011 TA_F07_2013 TA_F09_2013 	///
		TA_F03_2009 TA_F05_2009 TA_F03_2011 TA_F05_2011 TA_F03_2013 TA_F05_2013 	///
		MAT_F09_2009 LP_F09_2009 MAT_F09_2011 LP_F09_2011 MAT_F09_2013 LP_F09_2013 	///
		MAT_F05_2009 LP_F05_2009 MAT_F05_2011 LP_F05_2011 MAT_F05_2013 LP_F05_2013 	///
		IDEB_F09_2009 IDEB_F09_2011 IDEB_F09_2013 									///
		IDEB_F05_2009 IDEB_F05_2011 IDEB_F05_2013 {
			eststo: reg `var' resultado $estrato if  group!=. & munic == 13,   vce(cluster group)  
		}	
		global regressions*
		outreg2 [$regressions] using "$descriptives/Balance test for schools_Manaus.xls", nor nocons tstat  noparen  dec(2) replace
	
		/*
		**
		*Overall
		*-----------------------------------------------------------------------------------------------------------------*
		estimates clear
		foreach var in  DSU_F14 DSU_F58 TDI_F03 TDI_F05 TDI_F07 TDI_F09 ///
		TA_F07_2009 TA_F09_2009 TA_F07_2011 TA_F09_2011 TA_F07_2013 TA_F09_2013 ///
		TA_F03_2009 TA_F05_2009 TA_F03_2011 TA_F05_2011 TA_F03_2013 TA_F05_2013 ///
		MAT_F09_2009 LP_F09_2009 MAT_F09_2011 LP_F09_2011 MAT_F09_2013 LP_F09_2013 ///
		MAT_F05_2009 LP_F05_2009 MAT_F05_2011 LP_F05_2011 MAT_F05_2013 LP_F05_2013 ///
		IDEB_F09_2009 IDEB_F09_2011 IDEB_F09_2013 ///
		IDEB_F05_2009 IDEB_F05_2011 IDEB_F05_2013 {
			 eststo: reg `var' resultado $estrato if  group!=.,   vce(cluster group)  
		}	
		global regressions*
		outreg2  [$regressions]  using "$descriptives/Balance test for schools_Overall.xls", nor nocons tstat  noparen replace
		*/
		
		**
		*Organizing
		*-----------------------------------------------------------------------------------------------------------------*
		import  	delimited "$descriptives/Balance test for schools_Joinville.txt", clear  
		gen 		obs = _n
		keep		 if obs == 5 | obs == 26
			
		drop v1 obs
		sxpose, clear force
		
		gen 	dec = "% teachers in 1st to 5th grade with undergrad" in 1 
		replace dec = "% teachers in 6th to 9th grade with undergrad" in 2
		replace dec = "Age grade distortion 3rd grade (2013)" in 3
		replace dec = "Age grade distortion 5th grade (2013)" in 4
		replace dec = "Age grade distortion 7th grade (2013)" in 5
		replace dec = "Age grade distortion 9th grade (2013)" in 6
		replace dec = "Grade-promotion 7th grade (2009)" in 7
		replace dec = "Grade-promotion 9th grade (2009)" in 8
		replace dec = "Grade-promotion 7th grade (2011)" in 9
		replace dec = "Grade-promotion 9th grade (2011)" in 10
		replace dec = "Grade-promotion 7th grade (2013)" in 11
		replace dec = "Grade-promotion 9th grade (2013)" in 12
		replace dec = "Grade-promotion 3rd grade (2009)" in 13
		replace dec = "Grade-promotion 5th grade (2009)" in 14
		replace dec = "Grade-promotion 3rd grade (2011)" in 15
		replace dec = "Grade-promotion 5th grade (2011)" in 16
		replace dec = "Grade-promotion 3rd grade (2013)" in 17
		replace dec = "Grade-promotion 5th grade (2013)" in 18
		replace dec = "Math performance 9th grade (2009)" in 19
		replace dec = "Reading performance 9th grade (2009)" in 20
		replace dec = "Math performance 9th grade (2011)" in 21
		replace dec = "Reading performance 9th grade (2011)" in 22
		replace dec = "Math performance 9th grade (2013)" in 23
		replace dec = "Reading performance 9th grade (2013)" in 24
		replace dec = "Math performance 5th grade (2009)" in 25
		replace dec = "Reading performance 5th grade (2009)" in 26
		replace dec = "Math performance 5th grade (2011)" in 27
		replace dec = "Reading performance 5th grade (2011)" in 28
		replace dec = "Math performance 5th grade (2013)" in 29
		replace dec = "Reading performance 5th grade (2013)" in 30
		replace dec = "IDEB 9th grade (2009)" in 31
		replace dec = "IDEB 9th grade (2011)" in 32
		replace dec = "IDEB 9th grade (2013)" in 33
		replace dec = "IDEB 5th grade (2009)" in 34
		replace dec = "IDEB 5th grade (2011)" in 35
		replace dec = "IDEB 5th grade (2013)" in 36
		order 	dec
		set 	obs 38
		replace _var1 = "Joinville" in 37
		replace _var1 = "Beta" in 38
		replace _var2 = "Obs" in 38
		gen 	order = 1 in 37
		replace order = 2 in 38
		local i = 1
		forvalues order = 3(1)38 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		
		
		sort	order
		drop 	order
		export	excel using "$descriptives\Table A10.xls",  replace
		import  delimited   "$descriptives/Balance test for schools_Manaus.txt", clear  
		gen 	obs = _n
		keep 	if obs == 5 | obs == 26
		drop 	v1 obs
		sxpose, clear force
		set 	obs 38
		replace _var1 = "Manaus" in 37
		replace _var1 = "Beta" in 38
		replace _var2 = "Obs" in 38
		gen 	order = 1 in 37
		replace order = 2 in 38
		local i = 1
		forvalues order = 3(1)38 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		
		sort 	order
		drop 	order
		export	 excel using "$descriptives\Table A10.xls",  sheetmodify cell(D1)
		erase "$descriptives/Balance test for schools_Joinville.txt"
		erase "$descriptives/Balance test for schools_Manaus.txt"
		erase "$descriptives/Balance test for schools_Manaus.xls"
		erase "$descriptives/Balance test for schools_Joinville.xls"
	}
		
			
	**
	**Table A11
	*---------------------------------------------------------------------------------------------------------------------*
	{
		set seed 1257866
		foreach grade in 3 5 7 9 {
			use  "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
				estimates clear
				if `grade' == 3 local variables hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age resp_educ_1   resp_educ_2   resp_educ_3  
				if `grade' != 3 local variables hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age mother_educ_1 mother_educ_2 mother_educ_3 gender color_white
				
				foreach var of local variables {
					replace `var' = `var'*100 if cd_etapa_avaliada_turma == `grade'
				}

				*Regression of the percentage of missings 
				*-------------------------------------------------------------------------------------------------------------*
				foreach var in `variables' {
					gen 	miss_`var' = 1 if  missing(`var') & cd_etapa_avaliada_turma == `grade' 
					replace miss_`var' = 0 if !missing(`var') & cd_etapa_avaliada_turma == `grade'
					eststo:  reg  miss_`var' resultado $estrato if cd_etapa_avaliada_turma == `grade', cluster(cd_escola) 
				}
				global regressions*
				outreg2  [$regressions]  using "$descriptives/missing`grade'.xls", nor nocons tstat  noparen  dec(2) replace	
		}
				

		**
		*Organizing
		*-----------------------------------------------------------------------------------------------------------------*
		import  	delimited "$descriptives/missing3.txt", clear  
		gen 		obs = _n
		keep		 if obs == 5 | obs == 20
			
		drop v1 obs
		sxpose, clear force
		set obs 13
		
		
		
		gen 	dec = "Access to paved street" in 1 
		replace dec = "Access to electricity" in 2
		replace dec = "Access to piped water" in 3
		replace dec = "Access to garbage collection" in 4
		replace dec = "Beneficiary of Bolsa Família" in 5
		replace dec = "Adequate age for their grade " in 6
		replace dec = "Mother education: incomplete elementary school" in 7
		replace dec = "Mother education: incomplete high school" in 8
		replace dec = "Mother education: at least high school degree" in 9

		//
		replace _var1 = "Third-grade" in 10
		replace _var1 = "Beta" in 11
		replace _var2 = "Obs" in 11
		gen 	order = 1 in 10
		replace order = 2 in 11
		local i = 1
		forvalues order = 3(1)11 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		
		sort	order
		drop 	order
		order dec 
		set obs 13
		replace dec = "Gender: male"  in 12
		replace dec = "Color:  white" in 13
		export	excel using "$descriptives\Table A11.xls",  replace
		
		//
		import  delimited    "$descriptives/missing5.txt", clear  
		gen 	obs = _n
		keep		 if obs == 5 | obs == 20
		drop 	v1 obs
		sxpose, clear force
		set obs 13
		replace _var1 = "Fifth-grade" in 12
		replace _var1 = "Beta" in 13
		replace _var2 = "Obs" in 13
		gen 	order = 1 in 12
		replace order = 2 in 13
		local i = 1
		forvalues order = 3(1)13 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		sort order
		drop order
		export	 excel using "$descriptives\Table A11.xls",  sheetmodify cell(D1)
		
		//
		import  delimited    "$descriptives/missing7.txt", clear  
		gen 	obs = _n
		keep		 if obs == 5 | obs == 20
		drop 	v1 obs
		sxpose, clear force
		set obs 13
		replace _var1 = "Seventh-grade" in 12
		replace _var1 = "Beta" in 13
		replace _var2 = "Obs" in 13
		gen 	order = 1 in 12
		replace order = 2 in 13
		local i = 1
		forvalues order = 3(1)13 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		sort order	
		drop order
		export	 excel using "$descriptives\Table A11.xls",  sheetmodify cell(F1)
		
		//
		import  delimited    "$descriptives/missing9.txt", clear  
		gen 	obs = _n
		keep		 if obs == 5 | obs == 20
		drop 	v1 obs
		sxpose, clear force
		set obs 13
		replace _var1 = "Ninth-grade" in 12
		replace _var1 = "Beta" in 13
		replace _var2 = "Obs" in 13
		gen 	order = 1 in 12
		replace order = 2 in 13
		local i = 1
		forvalues order = 3(1)13 {
			replace order = `order' in `i'
			local i = `i' + 1
		}
		sort order	
		drop order
		export	 excel using "$descriptives\Table A11.xls",  sheetmodify cell(H1)

		foreach grade in 3  5 7 9 {
			erase "$descriptives/missing`grade'.txt"
			erase "$descriptives/missing`grade'.xls"		
		}
	}
	
	
	**
	**Table A12 ok
	*---------------------------------------------------------------------------------------------------------------------*
	//testando conjuntamente se as medias entre os grupos de T e C sao iguais. no iebaltab, testamos uma variavel de cada vez
	{
		use  "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
				
			mvtest means	 hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age resp_educ_1   resp_educ_2    					  if  cd_etapa_avaliada_turma == 3		, by(resultado)
			matrix a3 		= r(stat_m)
				
			foreach grade in 5 7 9 {
			mvtest means 	 hh_paved_street hh_electri hh_piped_water hh_garb_col bolsa_fam adequate_age mother_educ_1 mother_educ_2  gender color_white if  cd_etapa_avaliada_turma == `grade', by(resultado)
			matrix a`grade' = r(stat_m)
			}
			clear
				
			matrix  B = a3\a5\a7\a9
			svmat   B
			replace B6 = 3 in 1/4
			replace B6 = 5 in 5/8
			replace B6 = 7 in 9/12
			replace B6 = 9 in 13/16
			
			gen teste = ""
			foreach row in 1 5 9 13{
			replace teste = "Wilks" in `row'
			}
				
			foreach row in 2 6 10 14{
			replace teste = "Pillai" in `row'
			}	
				
			foreach row in 3 7 11 15{
			replace teste = "Lawley" in `row'
			}	
				
			foreach row in 4 8 12 16{
			replace teste = "Roy" in `row'
			}		
				
			tostring *, replace force

			foreach var of varlist B1 B2 B5 {
				replace `var' = substr(`var',1,4)
			}
	
			set obs 17
			replace teste = "Test" in 17
			replace B1 = "Statistic" in 17
			replace B2 = "F" in 17
			replace B3 = "df1" in 17
			replace B4 = "df2" in 17
			replace B5 = "pvalue" in 17
			gen order = 1 in 17
			sort order B6 teste
			replace B6 = "Third-grade" in 2/5
			replace B6 = "Fifth-grade" in 6/9
			replace B6 = "Seventh-grade" in 10/13
			replace B6 = "Ninth-grade" in 14/17
			order B6 teste
			drop order
			export	 excel using "$descriptives\Table A12.xls",  replace
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

	
	/*
	**
	*Imperfect complience
	*---------------------------------------------------------------------------------------------------------------------*


























































/*
*Other descriptives
*-------------------------------------------------------------------------------------------------------------------------

*Contaminação*
*-------------------------------------------------------------------------------------------------------------------------
/* 
Turmas das escolas de controle que acabaram recebendo tratamento e as turmas das escolas de tratamento que aparentemente não receberam*/

use 	"$dtfinal/Teacher's data.dta", clear								//32 turmas que estão com missing no código da escola
keep 	 cd_turma cd_escola prof1_rp_38 prof1_rp_39 prof1_rp_40 			//respostas do professor 1 
destring cd_escola, replace
merge 	 m:1 cd_escola using "$dtfinal/Treatment and Comparison Groups.dta", keep(match master) nogen

*Perguntas que não deveriam ter sido respondidas por professores das escolas do grupo de controle
codebook cd_escola if prof1_rp_39 >= 1 & prof1_rp_39 <= 8 & resultado == 0
codebook cd_escola if prof1_rp_38 >= 1 & prof1_rp_38 <= 8 & resultado == 0
codebook cd_escola if prof1_rp_40 >= 1 & prof1_rp_40 <= 8 & resultado == 0

*Professores que responderam todas as questões de aplicação do programa e são das escolas do grupo de controle
gen 	a = 1 					if (prof1_rp_39 >= 1 & prof1_rp_39 <= 8) &  (prof1_rp_38 >= 1 & prof1_rp_38 <= 8) & (prof1_rp_40 >= 1 & prof1_rp_40 <= 8)  & resultado == 0

*Estatísticas para a == 1
codebook cd_turma 	      		if a == 1 												//29 turmas das escolas de controle acabaram participando do programa
gen 	controle_tratado = 1 	if a == 1 				 & resultado == 0				//vamos considerar midada se o professor tiver respondido as três questões acima 
replace controle_tratado = 0 	if controle_tratado != 1 & resultado == 0				//controle_tratado: controle que foi tratado

*Professores que não respondeam as questões de aplicação do programa e são das escolas do grupo de tratamento
gen 	b = 1 					if (prof1_rp_39 == .a ) &  (prof1_rp_38== .a ) & (prof1_rp_40 == .a )  & resultado == 1

*Estatísticas para b = 1
codebook cd_turma 	      		if b == 1 												//9 turmas das escolas tratadas que aparentemente não receberam o tratamento
gen 	trat_sem_trat = 1 		if b == 1 				& resultado == 1				//vamos considerar contamidada se o professor não tiver respondido as três questões acima 
replace trat_sem_trat = 0 		if trat_sem_trat != 1   & resultado == 1				//trat_sem_trat: tratado sem tratamento

*Relação de alunos contaminados
keep 	cd_turma cd_escola controle_tratado trat_sem_trat resultado
save	"$dtinter/Control classes with treatment.dta", replace

*Se a escola de controle tem uma turma que foi tratada, vamos considerá-la como contaminada
sort 	 cd_escola cd_turma
collapse (mean)controle_tratado trat_sem_trat resultado, by (cd_escola)			
replace  controle_tratado = 1 if controle_tratado > 0 & controle_tratado != . 
replace  trat_sem_trat    = 1 if trat_sem_trat    > 0 & trat_sem_trat    != . 

*Relação de escolas contaminadas
save 	"$dtinter/Control schools with treatment.dta", replace

*1*
*Estatísticas descritivas das escolas do grupo de controle contaminado versus do grupo de controle não contaminado
*-------------------------------------------------------------------------------------------------------------------------
use 	"$dtinter/Control schools with treatment.dta", clear
merge 	 1:1 cd_escola using "$dtinter/School characteristics.dta", keep(match master) nogen

*Labels
label var  WaterAccess   	"Access to piped water"
label var  EnergyAccess 	"Access to electricity"
label var  SewerAccess  	"Access do basic sanitation"
label var  Computer  		"School with computer"
label var  SportCourt  		"School with sport court"
label var  FilteredWater  	"School with filtered water"
label var  WasteCollection  "School with garbage collection"
label var  WasteRecycling   "School with recycling"
label var  ComputerLab   	"School with computer lab"
label var  ScienceLab   	"School with science lab"
label var  Library   		"School with library"
label var  ReadingRoom 		"School with reading room"

tabform  $infraestrutura using "$descriptives/Descriptive of control schools versus control treated.xls", by(controle_tratado) vertical nototal mtest bdec(3) level(95)

*2*
*Estatísticas descritivas das crianças de escolas contamidas com relação às crianças do grupo de controle que não foram contaminadas
*-------------------------------------------------------------------------------------------------------------------------
use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear

merge m:1 cd_turma using "$dtinter/Control classes with treatment.dta", nogen //vamos assumir que as turmas que estão listadas em Fin_Lit_pooled_data_clean.dta, mas que não aparecem na base de professores não foram contaminadas

label var sm 				"Proficiency"
label var pca_consump_sm	"Consumption index"
label var pca_save_sm 		"Saving index"
label var adequate_age 		"Adequate age for their grade"
label var hh_paved_street 	"Access to paved street"
label var hh_electri 		"Access to electricity"
label var hh_piped_water 	"Access to piped water"
label var hh_garb_col 		"Access to garbage collection"
label var bolsa_fam 		"Beneficiary of Bolsa Família"
label var resp_age_1 		"Age: less than 20 years"
label var resp_age_2 		"Age: 21 to 59 years"
label var resp_age_3 		"Age: more than 60 years"
label var resp_educ_1 		"Education: incomplete elementary school"
label var resp_educ_2 		"Education: incomplete high school"
label var resp_educ_3 		"Education: at least high school degree"
label var resp_occup_1 		"Occupation: formal labor market"
label var resp_occup_2 		"Occupation: informal labor market"
label var resp_occup_3 		"Occupation: unemployed"
label var gender 		    "Gender: male"
label var color_white 		"Color: white"
label var mother_educ_1 	"Mother education: incomplete elementary school"
label var mother_educ_2 	"Mother education: incomplete high school"
label var mother_educ_3 	"Mother education: at least high school degree"

tabform  $student using "$descriptives/Descriptive of control students versus control students treated.xls", by(controle_tratado) vertical nototal mtest bdec (3) level(95)

tab socio_rp_61 if controle_tratado == 1  
tab socio_rp_61 if trat_sem_trat == 1
*_________________________________________________________________________________________________________________________*



*Proficiency in Math and Portuguese - before and after treatment*
*-------------------------------------------------------------------------------------------------------------------------
use 	"$dtfinal/Treatment and Comparison Groups.dta", clear
keep  	cd_escola munic resultado LP_* MAT_* IDEB_* strata*
order 	cd_escola munic resultado LP_* MAT_* IDEB_* strata*
reshape long LP_F05_ LP_F09_ MAT_F05_ MAT_F09_ IDEB_F05_ IDEB_F09_, i(cd_escola munic resultado) j(ano)
merge 1:1 cd_escola ano using "$dtinter/Enrollment by school_2007-2017.dta", keep(match master)

*Performance by grade
foreach grade in 5 9 { 
	preserve
		collapse (mean)IDEB_F0`grade '_  LP_F0`grade '_ MAT_F0`grade '_ [pw = Enrollment`grade 'Grade], by(resultado ano)
		tempfile a`grade '
		save `a`grade ''
	restore
}

*Merging
use `a5', clear
merge 1:1 resultado ano using `a9', nogen
 
foreach subject in IDEB LP MAT {
	foreach grade in 5 9 {
		if "`subject'" == "IDEB" local title  = "IDEB"
		if "`subject'" == "LP"   local title  = "Desempenho em Português"
		if "`subject'" == "MAT"  local title  = "Desempenho em Matemática"
		if `grade' 	   == 5 	   local stitle = "5o ano do EF"
		if `grade'     == 9	   local stitle = "9o ano do EF"

		tw 	///
		(line `subject'_F0`grade'_ ano if resultado == 0, xline(2015) lwidth(0.5) lp(shortdash) ///  
		///
		connect(direct) recast(connected) ml(`subject'_F0`grade'_) mlabcolor(gs2) ///
		///
		msize(1.5) ms(o) mlabposition(12) color(gs12) mlabsize(2.5)) ///
		///
		(line `subject'_F0`grade'_ ano if resultado == 1, lwidth(0.5) lp(shortdash) saving(`subject'_F0`grade', replace) ///  
		///
		connect(direct) recast(connected) ml(`subject'_F0`grade'_) mlabcolor(gs2) ///
		///
		msize(1.5) ms(o) mlabposition(12) color(ebblue) mlabsize(2.5) ///
		///
		ylabel(, labsize(small) gmax angle(horizontal) format(%12.0fc)) ///
		///
		ytitle("", size(medsmall)) ///
		///
		xtitle("",) ///
		///
		xlabel(2007(2)2017, labsize(small)) ///
		///
		title("`title'", pos(12) size(medsmall) color(black)) ///
		///
		subtitle("`stitle'", pos(12) size(medsmall) color(black)) ///
		///
		graphregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) ///
		///
		plotregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) ///
		///
		legend(order(1 "Controle" 2 "Tratamento") region(lwidth(none)) cols(2) size(medsmall) position(6)) ///
		///
		ysize(5) xsize(7) ///
		///
		note("", color(black) fcolor(background) pos(7) size(small)))
	}
}

graph combine LP_F05.gph MAT_F05.gph IDEB_F05.gph, holes(4) imargin(0 0 0 0)
graph export  "$figures/Trends for treatment and comparison groups_5th grade.emf", replace
graph combine LP_F09.gph MAT_F09.gph IDEB_F09.gph, holes(4) imargin(0 0 0 0)
graph export  "$figures/Trends for treatment and comparison groups_9th grade.emf", replace
erase IDEB_F05.gph 
erase LP_F05.gph 
erase MAT_F05.gph
erase IDEB_F09.gph 
erase LP_F09.gph 
erase MAT_F09.gph 
*_________________________________________________________________________________________________________________________*



*The number of classrooms in teacher's dataset is different from the number of student's dataset
*----------------------------------------------------------------------------------------------------------------------------
*Classrooms in teacher's dataset
use 	"$dtfinal/Teacher's data.dta", clear								//32 turmas que estão com missing no código da escola
keep 	 cd_turma 
tempfile a
save 	`a'

*Classrooms in student's dataset
use 	"$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
keep 	cd_turma
duplicates drop
merge 	1:1 cd_turma using `a' 												//tem 34 turmas aqui que não estão na base de professores e essas turmas representam cerca de 900 alunos
*____________________________________________________________________________________________________________________________




*% of school classrooms included in treatment and comparison groups -> a school can have 10 classrooms, but only 5 in the program
*----------------------------------------------------------------------------------------------------------------------------

*Número de turmas das escolas de Joinville e Manaus
use 	"$dtinter/Classrooms in Manaus and Joinville_2015.dta", clear
collapse (sum) TClass3Grade TClass5Grade TClass7Grade TClass9Grade, by (cd_escola)
tempfile turmas
save    `turmas'

*Turmas das escolas dos grupos de tratamento e comparação
use 		"$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
keep 	 	cd_turma cd_etapa_aplicacao_turma cd_escola
duplicates  drop
gen 		id = 1

*Number of classrooms per school
collapse 	(sum) id, by (cd_etapa_aplicacao_turma cd_escola)
reshape 	wide id, i(cd_escola) j(cd_etapa_aplicacao_turma) 
merge 		1:1 cd_escola using `turmas', nogen keep(match master)

foreach i in 3 5 7 9{
	gen p_`i' =id`i'/TClass`i'Grade 
}

drop 		if cd_escola == .
merge 		1:1 cd_escola using "$dtfinal/Treatment and Comparison Groups.dta", keepusing(resultado) keep(match master) nogen
collapse 	(mean)p_*, by(resultado)
reshape 	long p_, i(resultado) j(etapa)
reshape 	wide p_, i(etapa) j(resultado)

graph bar (asis)p_0 p_1, graphregion(color(white)) bar(1, color(gs12))  bar(2, color(ebblue))   ///
///
over(etapa, sort(etapa) label(labsize(small))) ///
///
legend(order(1 "Controle" 2 "Tratamento") cols(2) size(medsmall)  region(lwidth(none))) ///
///
graphregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) ///
///
plotregion(color(white) fcolor(white) lcolor(white) icolor(white) ifcolor(white) ilcolor(white)) ///
///
blabel(bar, position(inside) orientation(horizontal) size(vsmall)  color(black) format (%12.2fc))   ///
///
title("Proporção de turmas nos grupos de tratamento e compararação por escola", pos(12) size(medsmall) color(black)) ///
///
subtitle(, pos(12) size(medsmall) color(black)) ///
///
ylabel(, labsize(small) gmax angle(horizontal) format (%12.2fc) ) ///
///
ytitle ("%", size(medsmall)) /// 
///
ysize(5) xsize(7) ///
///
note("" , color(black) fcolor(background) pos(7) size(small))
graph export "$figures/% of treated classrooms by school.emf", as(emf) replace		
*____________________________________________________________________________________________________________________________


erase "$dtinter/Control classes with treatment.dta"
erase "$dtinter/Control schools with treatment.dta"


	**
	*==========================================================================================*
	* Table A.2 -- Program implementation, 2015
	* (consolidated from the former 5h_Tables_Implementation.do + 5i_Implementation_to_LaTeX.py;
	*  rewritten in plain Stata: no Excel round-trip and no Python. Layout simplified to one
	*  column per grade, with the control/treatment/difference shown as rows.)
	*==========================================================================================*

	cap program drop starof
	program define starof, rclass
		args p
		local s = ""
		if `p' < 0.10 local s = "*"
		if `p' < 0.05 local s = "**"
		if `p' < 0.01 local s = "***"
		return local s = "`s'"
	end

	*--- Panel A: participation in the assessment and response to the questionnaires ---
	use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
	recode fl_blank_score  (0 = 100) (1 = 0)
	recode fl_blank_parent (0 = 100) (1 = 0)
	recode fl_socio_blank  (0 = 100) (1 = 0)
	replace fl_blank_parent = . if fl_blank_score == 0
	replace fl_socio_blank  = . if fl_blank_score == 0

	tempname PA PAP PAN
	matrix PA  = J(6,4,.)		// rows 1-3: assessment C, T, C-T ; rows 4-6: questionnaire C, T, C-T
	matrix PAP = J(2,4,.)		// p-values of the two difference rows
	matrix PAN = J(2,4,.)		// N (control + treatment) for each block
	local gi = 0
	foreach g in 3 5 7 9 {
		local ++gi
		if `g' == 3 local rv fl_blank_parent
		else        local rv fl_socio_blank
		local k = 0
		foreach v in fl_blank_score `rv' {
			local ++k
			qui summ `v' if resultado==0 & cd_etapa_aplicacao_turma==`g'
			matrix PA[3*`k'-2,`gi'] = r(mean)
			local nc = r(N)
			qui summ `v' if resultado==1 & cd_etapa_aplicacao_turma==`g'
			matrix PA[3*`k'-1,`gi'] = r(mean)
			matrix PAN[`k',`gi'] = `nc' + r(N)
			qui reg `v' resultado i.estrato if cd_etapa_aplicacao_turma==`g'
			matrix PA[3*`k',`gi']  = -_b[resultado]			// control - treatment
			matrix PAP[`k',`gi']   = 2*ttail(e(df_r), abs(_b[resultado]/_se[resultado]))
		}
	}

	*--- Panel B: when treated students received the textbook (grades 5/7/9 only) ---
	use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
	tab socio_rp_61, gen(d_when_receive)
	foreach var of varlist d_when* {
		replace `var' = 100 if `var' == 1
	}
	keep if resultado == 1
	tempname DEL
	matrix DEL = J(4,4,.)		// display rows: 1 Haven't, 2 End, 3 Middle, 4 Beginning ; cols = grades
	local idxmap 4 3 2 1
	local gi = 0
	foreach g in 3 5 7 9 {
		local ++gi
		if `g' == 3 continue			// third graders got the material at home; not asked
		forvalues r = 1/4 {
			local di : word `r' of `idxmap'
			qui summ d_when_receive`di' if cd_etapa_aplicacao_turma==`g'
			matrix DEL[`r',`gi'] = r(mean)
		}
	}

	*--- Panels C and D: teacher-reported use of the material (one teacher per class) ---
	use "$dtinter/Teacher's data.dta", clear
	rename (prof1_rp_* prof2_rp_* prof3_rp_*) (prof_rp_*_1 prof_rp_*_2 prof_rp_*_3)
	rename (teacher*_key cd_disciplina_prof*) (teacher_key_* cd_disciplina_prof_*)
	keep prof_* teacher_* cd_disciplina* cd_turma
	reshape long teacher_key_ cd_disciplina_prof_ prof_rp_01_ prof_rp_02_ prof_rp_03_ prof_rp_04_ ///
		prof_rp_05_ prof_rp_06_ prof_rp_07_ prof_rp_08_ prof_rp_09_ prof_rp_10_ prof_rp_11_ prof_rp_12_ prof_rp_13_ prof_rp_14_ prof_rp_15_ ///
		prof_rp_16_ prof_rp_17_ prof_rp_18_ prof_rp_19_ prof_rp_20_ prof_rp_21_ prof_rp_22_ prof_rp_23_ prof_rp_24_ prof_rp_25_ prof_rp_26_ ///
		prof_rp_27_ prof_rp_28_ prof_rp_29_ prof_rp_30_ prof_rp_31_ prof_rp_32_ prof_rp_33_ prof_rp_34_ prof_rp_35_ prof_rp_36_ prof_rp_37_ ///
		prof_rp_38_ prof_rp_39_ prof_rp_40_ prof_rp_41_ prof_rp_42_ prof_rp_43_ prof_rp_44_ prof_rp_45_ prof_rp_46_ prof_rp_47_ prof_rp_48_ ///
		prof_rp_49_ prof_rp_50_ prof_rp_51_ prof_rp_52_ prof_rp_53_ prof_rp_54_ prof_rp_55_ prof_rp_56_ prof_rp_57_ prof_rp_58_ prof_rp_59_ ///
		prof_rp_60_ prof_rp_61_ prof_rp_62_ prof_rp_63_ prof_rp_64_ prof_rp_65_ ///
		, i(cd_turma) j(prof)
	sort cd_turma prof
	drop if missing(teacher_key_)
	bys cd_turma: gen t = _N
	keep if (t == 1) | (t > 1 & !missing(prof_rp_40_))
	drop t
	bys cd_turma: gen t = _N
	keep if (t == 1) | (t > 1 & !missing(prof_rp_39_))
	drop t
	gsort cd_turma -prof_rp_40_ -prof_rp_39_
	egen cd_turmatag = tag(cd_turma)
	keep if cd_turmatag == 1
	drop cd_turmatag
	tempfile prof
	save `prof'

	use "$dtfinal/Fin_Lit_pooled_data_clean.dta", clear
	egen tag_turma = tag(cd_turma)
	keep if tag_turma == 1
	keep cd_escola cd_turma cd_etapa_aplicacao_turma estrato resultado
	merge 1:1 cd_turma using `prof', keep(1 3) nogen

	gen     semester = 1 if inlist(prof_rp_39_,1,2,3)
	replace semester = 2 if inlist(prof_rp_39_,4,5,6)
	replace semester = 3 if prof_rp_39_ == 7
	tab semester, gen(d_semester)
	tab prof_rp_40_, gen(d_content)
	foreach var of varlist d_semester* d_content* {
		replace `var' = 100 if `var' == 1
	}
	keep if resultado == 1

	tempname SEM CON
	matrix SEM = J(3,4,.)
	matrix CON = J(4,4,.)
	local gi = 0
	foreach g in 3 5 7 9 {
		local ++gi
		forvalues r = 1/3 {
			qui summ d_semester`r' if cd_etapa_aplicacao_turma==`g'
			matrix SEM[`r',`gi'] = r(mean)
		}
		forvalues r = 1/4 {
			qui summ d_content`r' if cd_etapa_aplicacao_turma==`g'
			matrix CON[`r',`gi'] = r(mean)
		}
	}

	*--- write the LaTeX fragment (label + one column per grade) ---
	file open tex using "$textables/TableA2.tex", write replace
	file write tex "% Generated by 2_Descriptives.do (implementation block) -- data rows only, do not edit by hand." _n
	file write tex " & 3rd grade & 5th grade & 7th grade & 9th grade \\" _n

	*Panel A (participation rates moved to the student balance table, tab:studentscar)
	file write tex "\multicolumn{5}{l}{\textit{\textbf{Panel A. When treated students received the textbook (\%)}}} \\" _n
	local vrow `" "Haven't received" "In the end of the year" "By the middle of the year" "Beginning of the year" "'
	forvalues r = 1/4 {
		local lab : word `r' of `vrow'
		file write tex "`lab'"
		forvalues c = 1/4 {
			if missing(DEL[`r',`c']) file write tex " & ---"
			else file write tex " & " (strtrim(string(DEL[`r',`c'],"%9.1f")))
		}
		file write tex " \\" _n
	}

	*Panel B (semester)
	file write tex "\addlinespace" _n
	file write tex "\multicolumn{5}{l}{\textit{\textbf{Panel B. Semester in which teachers used the textbook (\% of treated classes)}}} \\" _n
	local crow `" "Only in the 1st semester" "Only in the 2nd semester" "All year" "'
	forvalues r = 1/3 {
		local lab : word `r' of `crow'
		file write tex "`lab'"
		forvalues c = 1/4 {
			if missing(SEM[`r',`c']) file write tex " & "
			else file write tex " & " (strtrim(string(SEM[`r',`c'],"%9.1f")))
		}
		file write tex " \\" _n
	}

	*Panel C (coverage)
	file write tex "\addlinespace" _n
	file write tex "\multicolumn{5}{l}{\textit{\textbf{Panel C. Share of the textbook covered (\% of treated classes)}}} \\" _n
	local drow `" "Less than 40\%" "Between 40\% and 60\%" "Between 60\% and 80\%" "More than 80\%" "'
	forvalues r = 1/4 {
		local lab : word `r' of `drow'
		file write tex "`lab'"
		forvalues c = 1/4 {
			if missing(CON[`r',`c']) file write tex " & "
			else file write tex " & " (strtrim(string(CON[`r',`c'],"%9.1f")))
		}
		file write tex " \\" _n
	}

	file close tex

	display "IMPLEMENTATION_TABLE_DONE"

*/
*/
*/
